#!/bin/bash

# USAGE: make-cover "Title" "Author" output.png

#
# Variables
#

TITLE=$1
AUTHOR=$2
OUTPUT=$3

AUTHOR_IMAGE=/tmp/author-$$.png
BACKGROUND_IMAGE=/tmp/background-$$.png
TITLE_IMAGE=/tmp/title-$$.png
LINE_IMAGE=/tmp/line-$$.png

#
# Title
#

# Create the border lines.
convert -size 700x2 canvas:white \
	-stroke black -strokewidth 10 \
    -draw "line 0,0 700,0" \
    $LINE_IMAGE 

# Create the title for the top part of the screen.
convert -size 700x -background white -fill black \
	-gravity Center \
	-font Gentium-Basic-Bold -pointsize 72 \
	caption:"$TITLE" \
	$TITLE_IMAGE

# Create the author name on the bottom.
convert -size 700x -background white -fill black \
	-gravity Center \
	-font Gentium-Basic-Bold -pointsize 64 \
	caption:"$AUTHOR" \
	$AUTHOR_IMAGE

# Combine the titles with the lines.
montage \
	-geometry 700x \
	$LINE_IMAGE $TITLE_IMAGE $LINE_IMAGE \
	-tile 1x \
        $TITLE_IMAGE

# Create a white background image to populate.
convert -size 800x1200 canvas:white \
        $BACKGROUND_IMAGE

# Combine everything together.
composite -geometry +50+200 $TITLE_IMAGE \
        $BACKGROUND_IMAGE $BACKGROUND_IMAGE
composite -geometry +50+1000 $AUTHOR_IMAGE \
        $BACKGROUND_IMAGE $BACKGROUND_IMAGE

# Move it into the output location.
mv $BACKGROUND_IMAGE $OUTPUT

# Clean up the rest of the files.
rm $AUTHOR_IMAGE $TITLE_IMAGE $LINE_IMAGE
